export enum EtatDefi {
  CHOIX_THEME = 'CHOIX_THEME',
  DEFI_CHALLENGER = 'DEFI_CHALLENGER',
  DEFI_CHAMPION = 'DEFI_CHAMPION',
  VERIF_DEFI_CHALLENGER = 'VERIF_DEFI_CHALLENGER',
  FIN_DEFI = 'FIN_DEFI',
}
