export enum EtatQuestion {
  START_QUESTION = 'START_QUESTION',
  QUESTION_POSE = 'QUESTION_POSE',
  CHOIX_MODE_QUESTION = 'CHOIX_MODE_QUESTION',
  REPONSES_PROPOSEES = 'REPONSES_PROPOSEES',
  REPONSE_JOUEUR_DONNEE = 'REPONSE_JOUEUR_DONNEE',
  BONNE_REPONSE_AFFICHEE = 'BONNE_REPONSE_AFFICHEE',
}
